
package com.fengjing.framework.webservice.jaxws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://service.jaxws.webservice.framework.fengjing.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param user
     * @return
     *     returns com.fengjing.framework.webservice.jaxws.client.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "print", targetNamespace = "http://service.jaxws.webservice.framework.fengjing.com/", className = "com.fengjing.framework.webservice.jaxws.client.Print")
    @ResponseWrapper(localName = "printResponse", targetNamespace = "http://service.jaxws.webservice.framework.fengjing.com/", className = "com.fengjing.framework.webservice.jaxws.client.PrintResponse")
    public User print(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.jaxws.webservice.framework.fengjing.com/", className = "com.fengjing.framework.webservice.jaxws.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.jaxws.webservice.framework.fengjing.com/", className = "com.fengjing.framework.webservice.jaxws.client.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @return
     *     returns java.util.List<com.fengjing.framework.webservice.jaxws.client.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://service.jaxws.webservice.framework.fengjing.com/", className = "com.fengjing.framework.webservice.jaxws.client.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://service.jaxws.webservice.framework.fengjing.com/", className = "com.fengjing.framework.webservice.jaxws.client.GetAllUsersResponse")
    public List<User> getAllUsers();

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloUsingSpring", targetNamespace = "http://service.jaxws.webservice.framework.fengjing.com/", className = "com.fengjing.framework.webservice.jaxws.client.SayHelloUsingSpring")
    @ResponseWrapper(localName = "sayHelloUsingSpringResponse", targetNamespace = "http://service.jaxws.webservice.framework.fengjing.com/", className = "com.fengjing.framework.webservice.jaxws.client.SayHelloUsingSpringResponse")
    public String sayHelloUsingSpring(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
