//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:09:04 PM CST 
//


package com.fengjing.framework.webservice.springws.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fengjing.framework.webservice.springws.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StudentRequest_QNAME = new QName("http://www.example.org/student", "studentRequest");
    private final static QName _StudentResponse_QNAME = new QName("http://www.example.org/student", "studentResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fengjing.framework.webservice.springws.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StudentRequestType }
     * 
     */
    public StudentRequestType createStudentRequestType() {
        return new StudentRequestType();
    }

    /**
     * Create an instance of {@link StudentResponseType }
     * 
     */
    public StudentResponseType createStudentResponseType() {
        return new StudentResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StudentRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/student", name = "studentRequest")
    public JAXBElement<StudentRequestType> createStudentRequest(StudentRequestType value) {
        return new JAXBElement<StudentRequestType>(_StudentRequest_QNAME, StudentRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StudentResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/student", name = "studentResponse")
    public JAXBElement<StudentResponseType> createStudentResponse(StudentResponseType value) {
        return new JAXBElement<StudentResponseType>(_StudentResponse_QNAME, StudentResponseType.class, null, value);
    }

}
