//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:09:04 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/student", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.fengjing.framework.webservice.springws.domain;
