//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:09:04 PM CST 
//


package com.fengjing.framework.webservice.springws.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for studentRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="studentRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Subject1" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Subject2" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Subject3" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "studentRequestType", propOrder = {
    "name",
    "subject1",
    "subject2",
    "subject3"
})
public class StudentRequestType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Subject1")
    protected int subject1;
    @XmlElement(name = "Subject2")
    protected int subject2;
    @XmlElement(name = "Subject3")
    protected int subject3;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the subject1 property.
     * 
     */
    public int getSubject1() {
        return subject1;
    }

    /**
     * Sets the value of the subject1 property.
     * 
     */
    public void setSubject1(int value) {
        this.subject1 = value;
    }

    /**
     * Gets the value of the subject2 property.
     * 
     */
    public int getSubject2() {
        return subject2;
    }

    /**
     * Sets the value of the subject2 property.
     * 
     */
    public void setSubject2(int value) {
        this.subject2 = value;
    }

    /**
     * Gets the value of the subject3 property.
     * 
     */
    public int getSubject3() {
        return subject3;
    }

    /**
     * Sets the value of the subject3 property.
     * 
     */
    public void setSubject3(int value) {
        this.subject3 = value;
    }

}
