
package com.fengjing.framework.spring.jax.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://service.ws.jax.spring.framework.fengjing.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.fengjing.framework.spring.jax.ws.client.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "print", targetNamespace = "http://service.ws.jax.spring.framework.fengjing.com/", className = "com.fengjing.framework.spring.jax.ws.client.Print")
    @ResponseWrapper(localName = "printResponse", targetNamespace = "http://service.ws.jax.spring.framework.fengjing.com/", className = "com.fengjing.framework.spring.jax.ws.client.PrintResponse")
    public User print(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.ws.jax.spring.framework.fengjing.com/", className = "com.fengjing.framework.spring.jax.ws.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.ws.jax.spring.framework.fengjing.com/", className = "com.fengjing.framework.spring.jax.ws.client.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloUsingSpring", targetNamespace = "http://service.ws.jax.spring.framework.fengjing.com/", className = "com.fengjing.framework.spring.jax.ws.client.SayHelloUsingSpring")
    @ResponseWrapper(localName = "sayHelloUsingSpringResponse", targetNamespace = "http://service.ws.jax.spring.framework.fengjing.com/", className = "com.fengjing.framework.spring.jax.ws.client.SayHelloUsingSpringResponse")
    public String sayHelloUsingSpring(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.fengjing.framework.spring.jax.ws.client.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://service.ws.jax.spring.framework.fengjing.com/", className = "com.fengjing.framework.spring.jax.ws.client.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://service.ws.jax.spring.framework.fengjing.com/", className = "com.fengjing.framework.spring.jax.ws.client.GetAllUsersResponse")
    public List<User> getAllUsers();

}
